# Generated by Django 6.0.1 on 2026-02-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, default='', max_length=20)),
                ('current_semester', models.IntegerField(default=1)),
                ('semester_start_date', models.DateField(blank=True, null=True)),
                ('semester_end_date', models.DateField(blank=True, null=True)),
                ('working_days', models.CharField(default='mon-sat', max_length=20)),
                ('periods_per_day', models.IntegerField(default=6)),
                ('period_duration_minutes', models.IntegerField(default=60)),
                ('break_period_position', models.IntegerField(default=0)),
                ('max_hours_per_lecturer_per_week', models.IntegerField(default=0)),
                ('lab_duration_periods', models.IntegerField(default=2)),
                ('allow_consecutive_labs', models.BooleanField(default=True)),
                ('clear_existing_before_regen', models.BooleanField(default=True)),
                ('enable_diary_auto_logging', models.BooleanField(default=True)),
                ('allow_lecturer_requests', models.BooleanField(default=True)),
                ('admin_email_for_alerts', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('semester_start_date', models.DateField(blank=True, null=True)),
                ('semester_end_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedTimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, default='', max_length=20)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, default='', max_length=80)),
                ('lecturer_username', models.CharField(blank=True, default='', max_length=150)),
                ('lecturer_full_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject_code', models.CharField(blank=True, default='', max_length=50)),
                ('subject_name', models.CharField(blank=True, default='', max_length=200)),
                ('class_code', models.CharField(blank=True, default='', max_length=50)),
                ('class_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject_type', models.CharField(blank=True, default='', max_length=20)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.semesterarchive')),
            ],
            options={
                'ordering': ['day', 'period', 'lecturer_username'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('timetable_view', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=10)),
                ('time_format', models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='24h', max_length=10)),
                ('diary_email_alerts', models.BooleanField(default=False)),
                ('diary_only_important', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
