# Generated by Django 6.0.1 on 2026-02-03 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(choices=[('system', 'System'), ('admin', 'Admin')], default='system', max_length=20)),
                ('entry_type', models.CharField(choices=[('timetable_generation_started', 'Timetable generation started'), ('timetable_generation_completed', 'Timetable generation completed'), ('timetable_regenerated', 'Timetable regenerated'), ('timetable_updated', 'Timetable updated'), ('subject_assigned', 'Subject assigned'), ('subject_rejected', 'Subject rejected'), ('clash_detected', 'Timetable clash detected'), ('announcement', 'Announcement')], max_length=40)),
                ('audience', models.CharField(choices=[('lecturers', 'Lecturers'), ('admins', 'Admins'), ('both', 'Both')], default='lecturers', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LecturerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('timetable_clash', 'Timetable clash'), ('subject_change', 'Subject change'), ('leave_unavailability', 'Leave / unavailability'), ('other_academic_issue', 'Other academic issue')], max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('seen', 'Seen'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reply', models.TextField(blank=True, default='')),
                ('admin_replied_at', models.DateTimeField(blank=True, null=True)),
                ('admin_replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_replies', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
