# Generated by Django 6.0.1 on 2026-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
