# Generated by Django 6.0.1 on 2026-02-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryentry_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='entry_type',
            field=models.CharField(choices=[('timetable_generation_started', 'Timetable generation started'), ('timetable_generation_completed', 'Timetable generation completed'), ('timetable_regenerated', 'Timetable regenerated'), ('timetable_updated', 'Timetable updated'), ('subject_assigned', 'Subject assigned'), ('subject_rejected', 'Subject rejected'), ('clash_detected', 'Timetable clash detected'), ('announcement', 'Announcement'), ('progress_reminder_50', 'Progress reminder (50%)'), ('progress_reminder_75', 'Progress reminder (75%)'), ('progress_reminder_end_soon', 'Progress reminder (end approaching)'), ('weekly_summary', 'Weekly summary')], max_length=40),
        ),
    ]
