# Generated by Django 6.0.1 on 2026-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_add_class_code_subject_class_timetable_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
